### ISSUE TITLE
Displaying ticket's subjects in the queue view

### ISSUE THREAD

**Issue by 0RoyTr** [Centuran/OTRS-Community-Edition#16]
Hello

I don't know if it is a good place to report this kinds of issue....

After last upgrade otrs from 6.0.32 to 6.0.38 i notice problems with displaying tickets in queue view. Tickets's subjects merging with the placed below information.

![otrs_issue](https://user-images.githubusercontent.com/125434045/218950972-db4a0037-796e-4d34-8613-4cae25296052.jpg)

**Comment by odyniec** [comment]
Thanks for reporting the issue. This has now been fixed in 94fc938 and will be included in the upcoming release.

If you want to fix it in your system for the time being, download the modified file [AgentTicketOverviewPreview.tt](https://github.com/Centuran/OTRS-Community-Edition/blob/94fc9388741351adf3d3f3a2cfba46d6a9539afb/Kernel/Output/HTML/Templates/Standard/AgentTicketOverviewPreview.tt) and place it under `Custom/Kernel/Output/HTML/Templates/Standard/`.
